// Generated by https://quicktype.io

export interface ScreenshotapiResponse {
  screenshot: string;
  url: string;
  created_at: Date;
  is_fresh: boolean;
  token: string;
  output: string;
  file_type: string;
  wait_for_event: string;
  ttl: Date;
  error?: string;
}
